#site name
name: megan chen's website

email: contact.meganchen @ gmail . com

#git
github_username: meganchen
bitbucket_username: themeganchen
gitlab_username: meganchen
	
# Build settings
markdown: kramdown